apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.echoWebapp}}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.echoWebapp.service.port }}
      targetPort: 80
      name: web
  selector:
    {{- include "echo-app.webapp.labels" .  | lower | nindent 4}}
  type: ClusterIP
