apiVersion: v1
kind: Service
metadata:
  namespace: echo-app-ns
  name: echo-api-svc
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: api
  selector:
    app: echo-app
    tier: back
  type: ClusterIP