{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}-ingress
  {{- with .Values.ingress.annotations}}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName}}
  rules:
  - host: {{ .Values.ingress.url}}
    http:
      paths:
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.echoWebapp.name}}-svc
            port:
              number: 9000
      - path: /api/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.echoApi.name}}-svc
            port:
              number: {{ .Values.echoApi.service.port}}
{{- end }}