apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.echoDb.name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 1433
      targetPort: 1433
      name: db
  selector:
    {{- include "echo-app.db.labels" .  | lower | nindent 6 }}
  clusterIP: None