apiVersion: batch/v1
kind: CronJob
metadata:
  name: echo-app-db-backup-job
  namespace: echo-app-ns
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: echo-app
            tier: backup
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - echo-app
                  - key: tier
                    operator: In
                    values:
                      - db
                topologyKey: "kubernetes.io/hostname"
          containers:
          - name: db-backup
            image: busybox
            args:
            - /bin/sh
            - -c
            - cp -r /backup/source/* /backup/target
            - sleep 3
            volumeMounts:
            - name: db-files
              mountPath: /backup/source
            - name: backup-folder
              mountPath: /backup/target
          restartPolicy: OnFailure
          volumes:
          - name: db-files
            persistentVolumeClaim:
              claimName: echo-app-db-pv-claim-echo-db-sts-0
          - name: backup-folder
            persistentVolumeClaim:
              claimName: echo-app-db-backup