apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: echo-app-pv-claim
  namespace: echo-app-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 3Gi
