apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.echoApi.name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.echoApi.service.port }}
      targetPort: 80
      name: api
  selector:
    {{- include "echo-app.api.labels" .  | lower | nindent 4}}
  type: ClusterIP