apiVersion: v1
data:
  connString: U2VydmVyPWVjaG8tZGItc3ZjLDE0MzM7SW5pdGlhbCBDYXRhbG9nPWVjaG8tbG9nO1VzZXIgSUQ9U0E7UGFzc3dvcmQ9UEBzc3cwcmQ7
  dbpass: UEBzc3cwcmQ=
kind: Secret
metadata:
  name: echo-api-db-secret
  namespace: echo-app-ns